apiVersion: v1
kind: Service
metadata:
  name: flusso-workflow-service
  labels:
    app: flusso-workflow
spec:
  type: LoadBalancer
  selector:
    app: flusso-workflow
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
